//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_Code_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int Chat_Id { get; set; }
        public string Message { get; set; }
        public System.DateTime Date_Of_Message { get; set; }
        public int Chat_Status_Id { get; set; }
        public Nullable<int> ChatRecieverUser_UserId { get; set; }
        public Nullable<int> ChatSenderUser_UserId { get; set; }
    }
}
