// <auto-generated />
namespace Final_Project_Code_First.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_UserWantBookTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_UserWantBookTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202002192154520_added_UserWantBookTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
